Update rest-client gem
- Changelogs: https://github.com/rest-client/rest-client/blob/cf3e5a115bcdb8f3344aeac0e45b44d67fac1a42/history.md#202
- This was required in order to be ruby 2.4 compatible.
  - Until version 2.0.1 of rest-client, running ruby 2.4 had cipher related
    issues.
    - Exact error: `KeyError: key not found: :ciphers`
    - See https://github.com/rest-client/rest-client/issues/569 for more information
- Version 2.0.0 removed the RestClient::MaxRedirectsReached exception class.
  - We added a shim for MaxRedirectsReached to maintain existing behavior.
- Updated webmock to be compatible with ruby 2.4+
  - Exact error:
```
NoMethodError: undefined method `close' for #<StubSocket:0x007f871cf99070>
Did you mean?  closed?
               clone
```

Co-authored-by: Andrew Aposhian <aaposhian@mavenlink.com>